### PR TITLE
Added Toast and Ratings

### PR DESCRIPTION
**Pull request by sri-rishi**
Toast types:

- Success Toast
- Error Toast
- Warning Toast

Rating types:

- Input 
- Badge read-only

### CODE REVIEW

**Review by shangkaul — APPROVED** [review]
Looks good to merge!

Tip: In the rating component, I am able to unselect middle stars too. I believe you'd require JS for this, not sure. Otherwise looks great!
Screenshot 2022-02-11 at 6 18 00 PM

**Comment by sri-rishi** [comment]
> Looks good to merge!
> 
> Tip: In the rating component, I am able to unselect middle stars too. I believe you'd require JS for this, not sure. Otherwise looks great! Screenshot 2022-02-11 at 6 18 00 PM

I have disabled all rating as it's requires JS and right now I am avoiding JS

**Comment by shangkaul** [comment]
> > Looks good to merge!
> > Tip: In the rating component, I am able to unselect middle stars too. I believe you'd require JS for this, not sure. Otherwise looks great! Screenshot 2022-02-11 at 6 18 00 PM
> 
> I have disabled all rating as it's requires JS and right now I am avoiding JS

Yep makes sense

**Review by Ankur9669 — CHANGES_REQUESTED** [review]
I have reviewed the code send me the working preview link so that i can approve the request

**Review by Ankur9669 — APPROVED** [review]
The Ui alos looks clean, looks good to merge

**Pull request merged**
